### ISSUE TITLE
Replace sofar css with gallery css

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/sofar#102]
Once the changes from #98 moved to the gallery, [docs/_static/css/fa_icon_style_draft.css](https://github.com/pyfar/sofar/pull/98/files#diff-ee26e7b492dcfc99b4c102ebc6ac7370ef6250707298ca46be3f8aa5ef01a071) should be replaced

**Comment by ahms5** [comment]
why not do it right now?
