### ISSUE TITLE
The read_sofa() function touches files/modifies time stamps

### ISSUE THREAD

**Issue by mberz** [pyfar/sofar#23]
The `read_sofa()` function opens the file with `'r+'` permission, resulting in touching the file and therefore modifying it, that is at least the time stamp. See 
https://github.com/pyfar/sofar/blob/1f214e02d6e957ee0f56dca0566bb71a5105dd53/sofar/sofar.py#L1416

I would expect, since this is a read-only operation, simple read-only permissions should suffice.

**Comment by f-brinkmann** [comment]
Fixed with release 0.2.0
