### ISSUE TITLE
Add `packaging` to the requirements

### ISSUE THREAD

**Issue by Firionus** [pyfar/sofar#74]
The package `packaging` (https://pypi.org/project/packaging/) is required for this library but missing from the requirements in `setup.py` and `requirements-dev.txt`. This made me run into this error:

```py
>>> import sofar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\MA\sofa2wav\.venv\Lib\site-packages\sofar\__init__.py", line 11, in <module>
    from .io import read_sofa, read_sofa_as_netcdf, write_sofa
  File "F:\MA\sofa2wav\.venv\Lib\site-packages\sofar\io.py", line 7, in <module>
    from packaging.version import parse
ModuleNotFoundError: No module named 'packaging'
```
The error was gone after installing `packaging`. It should be added to the requirements to make the installation easier.

Tested on sofar 1.1.1. 

<details>
  <summary>Environment Details</summary>

```shell
>rye --version
rye 0.22.0
commit: 0.22.0 (203a0f33f 2024-02-09)
platform: windows (x86_64)
self-python: cpython@3.12
symlink support: true
```
```ini
beautifulsoup4==4.12.3
certifi==2024.2.2
cffi==1.16.0
cftime==1.6.3
charset-normalizer==3.3.2
idna==3.6
netcdf4==1.6.5
numpy==1.26.4
packaging==23.2
pycparser==2.21
requests==2.31.0
sofar==1.1.1
soundfile==0.12.1
soupsieve==2.5
urllib3==2.2.0
```
</details>

Greetings from Ilmenau ⛰️ ☔ 👋

**Comment by f-brinkmann** [comment]
Hi Johannes, thanks for reporting :) This should be an easy fix, but I'm wondering why this never happend before. Can you check if the same occurs if you are using Python <3.12?

**Comment by Firionus** [comment]
Hey Fabian, thanks for the quick reply :mailbox_with_mail: :dash: 
The same error occurs when I try it with Python 3.8. 

This probably never happened before because I'm using the [rye](https://rye-up.com/) package/environment/installation manager  to run this in an unusually isolated Python environment. In a typical Python environment you'd expect packages that already depend on packaging, like conda, jupyter, matplotlib, QtPy, sphinx, black, just to name a few.

**Comment by f-brinkmann** [comment]
makes sense and thanks for checking. Will do a patch release soon :)

**Comment by f-brinkmann** [comment]
@Firionus can you ceck if #75 solves the issues by cling the repor and trying a local install with `pip install .`? I only added `packaging` to *setup.py* this should make sure to install `packaging` when installing *sofar* with `pip`. So it should already be there when installing packages from *requirements_dev.txt*, which is usually done as a second step.
