### ISSUE TITLE
"Descriptions" in `FreeFieldDirectivityTF` can't be added

### ISSUE THREAD

**Issue by Firionus** [pyfar/sofar#82]
sofar does not seem to allow the variable name `Descriptions` from the `FreeFieldDirectivityTF` convention. 

<details>
  <summary>Example Code</summary>
  
```pyconsole
> sofa.add_attribute("Descriptions", ["a", "b"])

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[54], line 1
----> 1 sofa3.add_attribute("Descriptions", ["a", "b"])

File [~\Documents\MA\e5-directivity\.venv\Lib\site-packages\sofar\sofa.py:578](http://localhost:8888/lab/workspaces/auto-M/tree/Documents/MA/e5-directivity/notebooks/~/Documents/MA/e5-directivity/.venv/Lib/site-packages/sofar/sofa.py#line=577), in Sofa.add_attribute(self, name, value)
    554 def add_attribute(self, name, value):
    555     """
    556     Add custom attribute to the SOFA object.
    557 
   (...)
    575 
    576     """
--> 578     self._add_entry(name, value, 'attribute', None)

File [~\Documents\MA\e5-directivity\.venv\Lib\site-packages\sofar\sofa.py:635](http://localhost:8888/lab/workspaces/auto-M/tree/Documents/MA/e5-directivity/notebooks/~/Documents/MA/e5-directivity/.venv/Lib/site-packages/sofar/sofa.py#line=634), in Sofa._add_entry(self, name, value, dtype, dimensions)
    631 if dtype == "attribute":
    632     if name.count("_") != 1 or \
    633             (name.startswith("Data_") and (name.count("_") == 0 or
    634                                            name.count("_") > 2)):
--> 635         raise ValueError((f"The name of {name} must have the "
    636                           "form VariableName_AttributeName"))
    637     if not name.startswith("GLOBAL_") and \
    638             name[:name.rindex("_")] not in self._convention:
    639         raise ValueError((f"Adding Attribute {name} requires "
    640                           f"variable {name[:name.rindex('_')]}"))

ValueError: The name of Descriptions must have the form VariableName_AttributeName
```

</details>

However, `GLOBAL_Description` and `Description`  are working, even though the latter is not specified in the standard. 

AES69-2022 says on page 50:

>If the same description is used for the whole file, the convention-specific attribute Description shall be used
(see table D.15.5B). If the description varies with the dimension M, the additional variable Descriptions of
dimensions [M S] shall be used for the individual descriptions (see table D.15.5G).

I think one issue is a typo at sofaconventions.org, where the variable is called "Description" instead of "Descriptions": https://www.sofaconventions.org/mediawiki/index.php/FreeFieldDirectivityTF

Another issue is that the standard wants you to use either `GLOBAL:Description` or `Descriptions` but sofar does not enforce that you use only one of them. Maybe for the better, I don't know.

For my application, I'll just go with `Description` for now and note the non-standard naming in `GLOBAL:Description`. 

I'm not sure what the best solution is for sofar. If the variable name is changed at sofaconcentions.org, wouldn't that break all existing files created with previous implementations? 

Tested with sofar 1.1.3 on Python 3.12.1.

**Comment by f-brinkmann** [comment]
Hi Johannes, I think (hope) everything is fine in sofar - but its easy to get wrong, because SOFA is complicated at times.

Might it be that you want to add a variable (an array of strings in this case) and not an attribute (attributes can only be strings in SOFA)? I tried to briefly explain it here: https://sofar.readthedocs.io/en/stable/examples.html#getting-information-about-sofa-objects.

**Comment by Firionus** [comment]
Oh yeah, you're right, this works:

```py
sofa.add_variable("Descriptions", [], "string", "MS")
```

What about the fact that [sofaconventions.org](https://www.sofaconventions.org/mediawiki/index.php/FreeFieldDirectivityTF) calls the variable "Description" (that's how sofar initiates it) and the standard calls it "Descriptions"? Where do I report that?

**Comment by f-brinkmann** [comment]
Hm, there would be two options. Changing the convention file (which might break compatability with existing files) or changing the standard (which would have to wait until the next revision in I think 2027). I would suggest we discuss this together with Piotr Majdak via Mail. Can you send me a Mail: https://www.tu.berlin/ak/ueber-uns/team/dr-fabian-brinkmann? I'll write to Piotr and Cc you if you want..
