### ISSUE TITLE
SourcePosition coordinates order error

### ISSUE THREAD

**Issue by gillesoldano** [pyfar/sofar#93]
In the section "Adding data to SOFA objects" the documentation example states "Now, the SOFA object contains a single HRIR - which is 1 for the left ear and 1 for the right ear - for a source at 0 degree azimuth, 90 degree elevation and a radius of 1.5 meter." where the example source coordinates are `[90, 0, 1.5]`. The azimuth and elevation coordinates order is inverted in respect to the default order stated in the SOFA conventions.

**Comment by f-brinkmann** [comment]
Thanks for reporting! This part of the sofar documention will be removed with an upcoming feature release in favor of the notebook at https://pyfar-gallery.readthedocs.io/en/latest/gallery/interactive/sofar_introduction.html#Getting-and-adding-data-to-SOFA-objects, where this is already fixed. I will just leave this issue open as long as it persists but not change anything :)
